name: NPM Package Updates

on: workflow_dispatch

jobs:
  update:
    name: Update NPM project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import GPG
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6.1.0
        with:
          gpg_private_key: ${{ secrets.BOT_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_PASSPHRASE }}
          git_config_global: true
          git_commit_gpgsign: true
          git_user_signingkey: true

      - name: Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
        run: |
          git switch -c dependency-updates-auto
          npm ci
          npm update --save
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> packages-updated.txt
          git add .
          git commit -m "Update npm packages"
          git push -u origin dependency-updates-auto

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --title "Update NPM packages" --body-file .github/PULL_REQUEST_TEMPLATE/dependencies.md
